### ISSUE TITLE
What is the selectivity profile of known p38 inhibitors

### ISSUE THREAD

**Issue by egonw** [openphacts/FederatedPhacts#2]

**Comment by Chris-Evelo** [comment]
I think this one does not have any federation problems.

**Comment by egonw** [comment]
@Chris-Evelo, but do we already have the SPARQL query for it?

**Comment by Chris-Evelo** [comment]
No, but I would be surprised if the original one used anything besides ChEMBL. That may need updates for the new ChEMBL RDF and updated to go the right place. Am I wrong?

**Comment by egonw** [comment]
That's something to check then. What's the (KNIME?) workflow they use, and which API methods did that use? With the latter info, we can check https://github.com/openphacts/OPS_LinkedDataApi/tree/master/api-config-files and see what the SPARQL looks like.
